# 69p ~ 70p

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[0]

np.int64(1)

In [9]:
b = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

# 71p

In [10]:
b.shape

(3, 3)

In [11]:
b.ndim

2

In [12]:
b.dtype

dtype('int64')

In [13]:
b.itemsize

8

In [14]:
b.size

9

In [15]:
b.dtype = "int32"

In [16]:
b.dtype

dtype('int32')

In [17]:
b.itemsize

4

# 72p

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3, 4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 73p

In [21]:
x = np.ones(5, dtype=np.int64)

In [22]:
x

array([1, 1, 1, 1, 1])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [25]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

# 74p ~ 75p

In [26]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [27]:
arr  = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [28]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x = np.array([[1, 2], [3, 4]])

In [35]:
y = np.array([[5, 6], [7, 8]])

In [36]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [37]:
np.vstack((x, y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 76p

In [39]:
a = np.arange(12)

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.shape

(12,)

In [42]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# 77p ~78p

In [44]:
array = np.arange(30).reshape(-1, 10)

In [45]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
arr1, arr2 = np.split(array, [3], axis=1)

In [47]:
arr1

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [48]:
arr2

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [49]:
a = np.array([1, 2, 3, 4, 5, 6])

In [50]:
a.shape

(6,)

In [51]:
a1 = a[np.newaxis, :]

In [52]:
a1

array([[1, 2, 3, 4, 5, 6]])

In [54]:
a1.shape

(1, 6)

In [55]:
a2 = a[:, np.newaxis]

In [56]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [57]:
a2.shape

(6, 1)

In [58]:
b = np.expand_dims(a, axis=1)

In [59]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
b.shape

(6, 1)